### ISSUE TITLE
Explanation on initServerSession

### ISSUE THREAD

**Issue by therladbsgh** [bernabe9/redux-react-session#10]
Could you explain more about how server sessions work with redux-react-session? In particular, the documentation regarding initServerSession:

    // server.js
    import { sessionService } from 'redux-react-session';

    // ...
    app.use((req, res) => {
      const store = createStrore();
      sessionService.initServerSession(store, req);
      // ...
    }
    // ...

If createStore() comes from redux (I'm assuming  createStrore is a typo), what parameters would I need to pass into it? Is there also any other configuration that needs to be done after `sessionService.initServerSession(store, req)`?

**Comment by umpc** [comment]
While I am not familiar with the exact use case for ```initServerSession```, ```req``` is expected to be a Map-type value with a ```cookie``` String-type key.

```initServerSession``` sets the session and/or user info based on the cookie data it finds in the ```req``` map.

The Usage section in the readme shows the inclusion of the ```sessionReducer```, so I would expect that it is needed in this case as well.

**Comment by bernabe9** [comment]
First of all, just clarify some concepts, when we have a server rendering the client makes the request to the server and then the server returns a response with the full rendered content. So, the problem here is that the client is who have the data for the authentication(for example in the cookies), but is the server who needs this data.

The server needs the authentication data for:
1) Detect if the route requested is valid for the user (if the route needs authentication)
2) Request something to an external API(using the authentication data)

Regarding to your questions:
`createStore()` is just a function that creates the redux storage, maybe that generates confusion. Here is how it looks without `createStore()`:

```javascript
// server.js
import { sessionService, sessionReducer } from 'redux-react-session';
import { combineReducers, createStore, compose, applyMiddleware } from 'redux';

// ...
app.use((req, res) => {
  // Add the sessionReducer
  const reducer = combineReducers({
    session: sessionReducer
  });
  const store = createStore(reducer, undefined, compose(applyMiddleware(thunkMiddleware)));
  sessionService.initServerSession(store, req);
  // ...
}
// ...
```

There is no more configuration for the server, although I will add an example for the server rendering since it's hard to understand.

**Comment by bernabe9** [comment]
Checkout the new server rendering example: https://github.com/bernabe9/redux-react-session/tree/master/examples/server%20rendering
